# Generated by Django 2.0 on 2019-12-01 09:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='fname',
            new_name='Fname',
        ),
        migrations.RenameField(
            model_name='user',
            old_name='lname',
            new_name='Lname',
        ),
    ]
